const genreOptions = [
    'Fiction',
    'Novel',
    'Mystery',
    'Narrative',
    'Science fiction',
    'Historical Fiction',
    'Romance novel',
    "Children's literature",
    'Thriller',
    'Genre fiction',
    'Self-help book',
    'Young adult fiction',
    'Memoir',
    'Horror',
    'Non-fiction',
    'Historical fantasy',
    'Biography',
    'Humor',
    'Literary fiction',
    'Fantasy',
    'History',
    'True crime',
    'Adventure fiction',
    'Poetry',
    'Graphic novel',
    "Women's fiction",
    'Science fantasy',
    'Autobiography',
    'Horror fiction',
    'Spirituality',
    'Fairy tale',
    'Magical Realism',
    'Short Story',
    'Romance',
    'Hybrid genre',
    'Postmodern literature',
    'Politics',
    'Dystopian Fiction',
    'Time Travel Fiction',
    'Erotic literature',
    'Cozy mystery',
    'Cookbook',
    'Personal development',
    'Coffee table book',
    'Dark comedy',
    'Travel literature',
    'Drama',
    'Contemporary romance',
    'Essay',
    'Western fiction',
    'Satire',
  ];

  export default genreOptions;